# Generated by Django 4.2.6 on 2023-10-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100, verbose_name='Enter your post name')),
                ('post_text', models.TextField(verbose_name='Enter your post text')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
