# Generated by Django 4.2.6 on 2023-11-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'news post', 'verbose_name_plural': 'news posts'},
        ),
    ]
