# Generated by Django 4.2.6 on 2023-11-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shorts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.URLField(max_length=50, null=True, unique=True),
        ),
    ]
